/**
 * Seed script for recipes
 * Run with: node scripts/seed-recipes.js
 * Requires: Ingredients and seed user. Run seed:ingredients first.
 */

const path = require("path");
const mongoose = require("mongoose");

try {
  require("dotenv").config({ path: path.join(__dirname, "..", ".env.local") });
} catch { }

const USER_ID = new mongoose.Types.ObjectId("69b713cc430c67e45cbaca6a");

// Recipe definitions: { title, ingredientNames: string[], instructions }
const RECIPES = [
  {
    title: "Classic Spaghetti Bolognese",
    ingredientNames: ["Spaghetti", "Ground beef", "Tomato sauce", "Onion", "Garlic", "Olive oil", "Parmesan", "Basil", "Salt", "Black pepper"],
    instructions: "Heat olive oil in a large pan over medium heat and sauté the chopped onion and minced garlic until softened and fragrant. Add the ground beef and cook until browned, breaking it up as it cooks. Stir in the tomato sauce, basil, salt, and black pepper, then let the sauce simmer gently for about 30 minutes to develop flavor. Meanwhile, cook the spaghetti in salted boiling water until al dente. Drain the pasta and serve topped with the Bolognese sauce and a generous sprinkle of Parmesan.",
  },
  {
    title: "Chicken Stir Fry",
    ingredientNames: ["Chicken breast", "Broccoli", "Bell pepper", "Soy sauce", "Garlic", "Ginger", "Vegetable oil", "Rice"],
    instructions: "Slice the chicken breast into thin strips and chop the broccoli and bell pepper into bite-sized pieces. Heat vegetable oil in a wok or large skillet over high heat and stir-fry the chicken until it is fully cooked and lightly browned. Add the vegetables along with minced garlic and grated ginger, cooking for a few minutes until the vegetables are tender-crisp. Stir in the soy sauce and toss everything together so it is evenly coated. Serve the stir fry hot over freshly cooked rice.",
  },
  {
    title: "Greek Salad",
    ingredientNames: ["Cucumber", "Tomato", "Red onion", "Feta cheese", "Olives", "Olive oil", "Lemon juice", "Oregano", "Salt"],
    instructions: "Chop the cucumber, tomato, and red onion into bite-sized pieces and place them in a large bowl. Add the olives and cubes of feta cheese on top of the vegetables. In a small drizzle, combine olive oil and lemon juice, then sprinkle in oregano and a pinch of salt. Pour the dressing over the salad and gently toss everything together until evenly coated. Serve immediately for a fresh and flavorful salad.",
  },
  {
    title: "Scrambled Eggs with Toast",
    ingredientNames: ["Eggs", "Butter", "Salt", "Black pepper", "Bread"],
    instructions: "Crack the eggs into a bowl and beat them well with a pinch of salt and black pepper until fully combined. Melt butter in a nonstick pan over medium heat, then pour in the eggs. Stir gently and continuously with a spatula, allowing soft curds to form as the eggs cook. Continue cooking until the eggs are just set but still soft. At the same time, toast the bread until golden brown, then serve the scrambled eggs alongside the warm toast.",
  },
  {
    title: "Beef Tacos",
    ingredientNames: ["Ground beef", "Tortilla", "Lettuce", "Tomato", "Cheese", "Salsa", "Lime", "Cumin", "Chili powder"],
    instructions: "Cook the ground beef in a skillet over medium heat, breaking it apart as it browns. Season the beef with cumin and chili powder and stir well so the spices coat the meat evenly. Warm the tortillas in a dry pan or microwave until soft and pliable. Assemble the tacos by filling each tortilla with seasoned beef, shredded lettuce, diced tomato, shredded cheese, and a spoonful of salsa. Finish with a squeeze of fresh lime juice before serving.",
  },
  {
    title: "Salmon with Lemon and Dill",
    ingredientNames: ["Salmon", "Lemon", "Dill", "Olive oil", "Garlic", "Salt", "Black pepper"],
    instructions: "Place the salmon fillets on a baking sheet and season them with salt, black pepper, and fresh dill. Drizzle olive oil over the fish and add minced garlic on top for extra flavor. Bake the salmon in a preheated oven at 400°F for about 12–15 minutes, or until the fish flakes easily with a fork. Just before serving, squeeze fresh lemon juice over the salmon to brighten the flavor.",
  },
  {
    title: "Vegetable Soup",
    ingredientNames: ["Carrots", "Celery", "Onion", "Potato", "Vegetable broth", "Tomato", "Garlic", "Thyme", "Salt", "Black pepper"],
    instructions: "In a large pot, sauté chopped onion, celery, carrots, and minced garlic in a little oil over medium heat until the vegetables begin to soften. Add the vegetable broth along with diced potato, chopped tomato, and thyme. Bring the mixture to a gentle boil, then reduce the heat and let it simmer for about 25 minutes until the vegetables are tender and the flavors are well combined. Season the soup with salt and black pepper to taste before serving.",
  },
  {
    title: "Chicken Caesar Salad",
    ingredientNames: ["Chicken breast", "Romaine", "Parmesan", "Caesar dressing", "Bread", "Lemon juice", "Black pepper"],
    instructions: "Season and grill or pan-fry the chicken breast until fully cooked and golden, then slice it into strips. Chop the romaine lettuce and place it in a large bowl, tossing it with Caesar dressing until evenly coated. Top the salad with the sliced chicken, shaved Parmesan cheese, and crunchy croutons made from toasted bread. Finish with a squeeze of fresh lemon juice and a sprinkle of black pepper before serving.",
  },
  {
    title: "Pancakes",
    ingredientNames: ["Flour", "Eggs", "Milk", "Baking powder", "Sugar", "Butter", "Maple syrup"],
    instructions: "1. Mix flour, baking powder, sugar. 2. Add eggs and milk, whisk. 3. Melt butter in pan, pour batter. 4. Flip when bubbles form. Serve with syrup.",
  },
  {
    title: "Pancakes",
    ingredientNames: ["Flour", "Eggs", "Milk", "Baking powder", "Sugar", "Butter", "Maple syrup"],
    instructions: "In a bowl, whisk together the flour, baking powder, and sugar until well combined. Add the eggs and milk, then whisk the mixture until a smooth batter forms. Heat a pan over medium heat and melt a little butter to coat the surface. Pour a portion of batter into the pan and cook until bubbles form on the surface, then flip and cook the other side until golden brown. Serve the pancakes warm with butter and maple syrup.",
  },
  {
    title: "Garlic Shrimp Pasta",
    ingredientNames: ["Shrimp", "Spaghetti", "Garlic", "Olive oil", "Lemon", "Parsley", "Red pepper flakes", "Salt"],
    instructions: "Cook the spaghetti in salted boiling water according to package instructions until al dente, then drain. In a large skillet, heat olive oil over medium heat and sauté the minced garlic until fragrant. Add the shrimp and cook until they turn pink and opaque. Toss the cooked pasta with the shrimp mixture, then add a squeeze of lemon juice, chopped parsley, red pepper flakes, and salt. Mix well and serve immediately.",
  },
  {
    title: "Omelette",
    ingredientNames: ["Eggs", "Butter", "Cheese", "Salt", "Black pepper"],
    instructions: "Crack the eggs into a bowl and beat them with a pinch of salt and black pepper until fully blended. Melt butter in a nonstick pan over medium heat and pour in the eggs, tilting the pan to spread them evenly. As the eggs begin to set, sprinkle cheese over one half of the omelette. Let it cook until mostly set, then gently fold it in half and slide it onto a plate to serve.",
  },
  {
    title: "Grilled Cheese Sandwich",
    ingredientNames: ["Bread", "Cheddar cheese", "Butter"],
    instructions: "Spread butter on the outside of each slice of bread. Place slices of cheddar cheese between the bread to form a sandwich. Heat a skillet over medium heat and cook the sandwich until the bread is golden brown and crispy on one side. Flip it carefully and cook the other side until the cheese is melted and the bread is evenly toasted. Slice and serve while warm.",
  },
  {
    title: "Roasted Chicken",
    ingredientNames: ["Whole chicken", "Olive oil", "Salt", "Black pepper", "Thyme", "Garlic", "Lemon"],
    instructions: "Rub the whole chicken with olive oil and season it generously with salt, black pepper, and thyme. Stuff the cavity with garlic cloves and lemon halves to add flavor as it cooks. Place the chicken in a roasting pan and roast in a preheated oven at 425°F for about 1 hour, or until the skin is golden and the juices run clear. Let the chicken rest for about 10 minutes before carving and serving.",
  },
  {
    title: "Mashed Potatoes",
    ingredientNames: ["Potato", "Butter", "Milk", "Salt", "Black pepper"],
    instructions: "Peel and cut the potatoes into chunks, then boil them in salted water until they are very tender when pierced with a fork. Drain the potatoes well and place them back in the pot or a bowl. Mash them with butter and warm milk until smooth and creamy. Season with salt and black pepper to taste, mixing until everything is well combined before serving.",
  },
  {
    title: "Tomato Basil Pasta",
    ingredientNames: ["Pasta", "Tomato", "Basil", "Garlic", "Olive oil", "Parmesan", "Salt"],
    instructions: "Cook the pasta in a pot of salted boiling water until al dente, then drain and set aside. In a skillet, heat olive oil over medium heat and sauté the minced garlic until fragrant. Add the diced tomatoes and let them simmer for about 10 minutes until they soften and release their juices. Stir in fresh basil and salt, then toss the sauce with the cooked pasta. Serve topped with grated Parmesan cheese.",
  },
  {
    title: "Chicken Noodle Soup",
    ingredientNames: ["Chicken breast", "Chicken broth", "Pasta", "Carrots", "Celery", "Onion", "Thyme", "Salt", "Black pepper"],
    instructions: "In a large pot, sauté chopped onion, carrots, and celery in a little oil until they begin to soften. Add the chicken broth, chicken breast, and thyme, then bring the soup to a gentle simmer and cook until the chicken is fully cooked. Remove the chicken, shred it into pieces, and return it to the pot. Add the pasta and cook until the noodles are tender, then season the soup with salt and black pepper before serving.",
  },
  {
    title: "Avocado Toast",
    ingredientNames: ["Bread", "Avocado", "Lemon juice", "Salt", "Red pepper flakes", "Eggs"],
    instructions: "Toast the bread slices until they are golden and crisp. In a small bowl, mash the avocado with lemon juice and a pinch of salt until creamy but still slightly chunky. Spread the avocado mixture evenly over the toast. Top each slice with a freshly fried egg and finish with a sprinkle of red pepper flakes before serving.",
  },
  {
    title: "Beef Stew",
    ingredientNames: ["Beef chuck", "Potato", "Carrots", "Onion", "Beef broth", "Tomato paste", "Bay leaves", "Thyme", "Salt", "Black pepper"],
    instructions: "Cut the beef chuck into chunks and brown it in a large pot over medium-high heat until well seared on all sides. Add the chopped onion and tomato paste, stirring for a few minutes until the onion softens and the paste darkens slightly. Pour in the beef broth and add the bay leaves and thyme, bringing the mixture to a gentle simmer. Add the diced potatoes and sliced carrots, then cover and let the stew cook slowly for about 2 hours until the beef is tender. Season with salt and black pepper before serving.",
  },
  {
    title: "Fish Tacos",
    ingredientNames: ["Tilapia", "Tortilla", "Cabbage", "Lime", "Cilantro", "Sour cream", "Avocado"],
    instructions: "Season the tilapia fillets with salt and cook them on a grill or skillet until flaky and cooked through. Warm the tortillas in a dry pan or microwave until soft and pliable. Fill each tortilla with shredded cabbage and pieces of fish, then add slices of avocado and a spoonful of sour cream. Finish with a squeeze of fresh lime juice and a sprinkle of chopped cilantro before serving.",
  },
  {
    title: "Caprese Salad",
    ingredientNames: ["Tomato", "Mozzarella", "Basil", "Olive oil", "Balsamic vinegar", "Salt", "Black pepper"],
    instructions: "Slice the tomatoes and mozzarella into even rounds and arrange them on a plate in alternating layers. Tuck fresh basil leaves between the slices for flavor and color. Drizzle olive oil and balsamic vinegar evenly over the top. Finish by sprinkling with salt and black pepper, then serve immediately.",
  },
  { title: "French Toast", ingredientNames: ["Bread", "Eggs", "Milk", "Cinnamon", "Butter", "Maple syrup"], instructions: "In a shallow bowl, whisk together the eggs, milk, and cinnamon until well combined. Dip each slice of bread into the mixture, allowing it to soak briefly on both sides. Melt butter in a skillet over medium heat and cook the soaked bread until golden brown on each side. Serve the French toast warm with maple syrup drizzled on top." },
  { title: "BLT Sandwich", ingredientNames: ["Bread", "Bacon", "Lettuce", "Tomato", "Mayonnaise"], instructions: "Cook the bacon in a skillet until crispy, then transfer it to a paper towel to drain excess grease. Toast the bread slices until lightly golden and spread mayonnaise on one side of each slice. Layer the bacon, fresh lettuce, and sliced tomato between the bread. Close the sandwich, slice if desired, and serve." },
  { title: "Quinoa Bowl", ingredientNames: ["Quinoa", "Chickpeas", "Cucumber", "Tomato", "Feta cheese", "Lemon juice", "Olive oil"], instructions: "Cook the quinoa according to package instructions and allow it to cool slightly. In a bowl, combine the quinoa with chickpeas, diced cucumber, chopped tomato, and crumbled feta cheese. Drizzle lemon juice and olive oil over the mixture and toss everything gently until evenly coated. Serve as a fresh and hearty bowl." },
  { title: "Lentil Soup", ingredientNames: ["Lentils", "Onion", "Carrots", "Celery", "Vegetable broth", "Cumin", "Garlic", "Salt"], instructions: "Heat oil in a pot and sauté the chopped onion, carrots, celery, and minced garlic until softened and fragrant. Add the lentils, vegetable broth, and cumin, stirring to combine. Bring the soup to a boil, then reduce the heat and let it simmer for about 40 minutes until the lentils are tender. Season with salt to taste before serving." },
  { title: "Honey Garlic Chicken", ingredientNames: ["Chicken breast", "Honey", "Garlic", "Soy sauce", "Rice vinegar", "Sesame seeds", "Green onions"], instructions: "In a small bowl, whisk together honey, minced garlic, soy sauce, and rice vinegar to create the sauce. Cook the chicken breast pieces in a skillet over medium heat until browned and cooked through. Pour the sauce over the chicken and let it simmer until it thickens slightly and coats the meat. Finish with a sprinkle of sesame seeds and chopped green onions before serving." },
  { title: "Spinach Salad", ingredientNames: ["Spinach", "Strawberries", "Feta cheese", "Walnuts", "Balsamic vinegar", "Olive oil"], instructions: "Place fresh spinach leaves in a large bowl and top with sliced strawberries, crumbled feta cheese, and chopped walnuts. In a small bowl, whisk together balsamic vinegar and olive oil to make a simple dressing. Drizzle the dressing over the salad and toss gently until everything is lightly coated. Serve immediately." },
  { title: "Tuna Salad", ingredientNames: ["Canned tuna", "Mayonnaise", "Celery", "Onion", "Lemon juice", "Salt", "Black pepper"], instructions: "Drain the canned tuna and place it in a bowl, then flake it apart with a fork. Add mayonnaise, finely chopped celery, diced onion, and a splash of lemon juice. Mix everything together until well combined and creamy. Season with salt and black pepper to taste, then serve on bread, crackers, or over greens." },
  { title: "Egg Fried Rice", ingredientNames: ["Rice", "Eggs", "Soy sauce", "Green onions", "Vegetable oil", "Garlic", "Peas"], instructions: "Heat vegetable oil in a large skillet or wok and scramble the eggs until just set, then remove them from the pan and set aside. Add a little more oil and sauté the minced garlic until fragrant. Stir-fry the day-old rice with peas, breaking up any clumps as it cooks. Return the eggs to the pan, add soy sauce and sliced green onions, and toss everything together until heated through." },
  { title: "Pesto Pasta", ingredientNames: ["Pasta", "Pesto", "Parmesan", "Cherry tomatoes", "Olive oil"], instructions: "Cook the pasta in salted boiling water until al dente, then drain and return it to the pot. Add pesto and toss the pasta until it is evenly coated. Stir in grated Parmesan and halved cherry tomatoes for extra flavor and freshness. Finish with a light drizzle of olive oil and serve warm." },
  { title: "Turkey Sandwich", ingredientNames: ["Bread", "Deli turkey", "Lettuce", "Tomato", "Mayonnaise", "Mustard"], instructions: "Spread mayonnaise and mustard evenly on the slices of bread. Layer the deli turkey, crisp lettuce, and sliced tomato on one piece of bread. Place the second slice on top to close the sandwich, pressing gently. Slice if desired and serve." },
  { title: "Baked Ziti", ingredientNames: ["Penne", "Tomato sauce", "Mozzarella", "Ricotta", "Parmesan", "Basil"], instructions: "Cook the penne in salted boiling water until just al dente, then drain. In a baking dish, layer the pasta with tomato sauce, spoonfuls of ricotta, and shredded mozzarella. Repeat the layers if desired and finish with a generous sprinkle of Parmesan and basil. Bake in a preheated oven at 350°F for about 30 minutes until bubbly and lightly golden on top." },
  { title: "Cobb Salad", ingredientNames: ["Lettuce", "Chicken breast", "Bacon", "Eggs", "Avocado", "Tomato", "Blue cheese", "Ranch dressing"], instructions: "Spread chopped lettuce across a large serving platter or bowl as the base. Arrange rows of cooked chicken breast, crispy bacon, chopped boiled eggs, sliced avocado, diced tomato, and crumbled blue cheese over the lettuce. Drizzle ranch dressing across the top or serve it on the side. Toss lightly before eating if desired." },
  { title: "Minestrone", ingredientNames: ["Vegetable broth", "Tomato", "Pasta", "Kidney beans", "Carrots", "Celery", "Onion", "Garlic", "Basil"], instructions: "In a large pot, sauté the chopped onion, carrots, celery, and minced garlic in a little oil until softened. Add vegetable broth, chopped tomatoes, and kidney beans, bringing the soup to a simmer. Stir in the pasta and basil and cook until the pasta is tender. Taste and adjust seasoning before serving." },
  { title: "Shrimp Scampi", ingredientNames: ["Shrimp", "Garlic", "Butter", "White wine", "Lemon", "Parsley", "Spaghetti"], instructions: "Cook the spaghetti in salted boiling water until al dente, then drain. In a skillet, melt butter and sauté minced garlic until fragrant. Add the shrimp and cook until pink, then pour in white wine and a squeeze of lemon juice. Stir in chopped parsley and toss the sauce with the cooked spaghetti before serving." },
  { title: "Chicken Quesadilla", ingredientNames: ["Chicken breast", "Tortilla", "Cheese", "Bell pepper", "Onion", "Salsa"], instructions: "Cook the chicken breast in a skillet until fully done, then slice it into strips. Place a tortilla in a hot pan and layer it with chicken, shredded cheese, sliced bell peppers, and onions. Fold the tortilla in half and cook until the outside is golden and the cheese has melted. Cut into wedges and serve with salsa." },
  { title: "Potato Salad", ingredientNames: ["Potato", "Mayonnaise", "Mustard", "Celery", "Onion", "Eggs", "Salt", "Black pepper"], instructions: "Boil the potatoes in salted water until tender and cook the eggs until hard-boiled, then let both cool slightly. Chop the potatoes and eggs into bite-sized pieces and place them in a bowl. Add mayonnaise, mustard, diced celery, and chopped onion, then mix gently until well combined. Season with salt and black pepper before serving." },
  { title: "Oatmeal", ingredientNames: ["Oats", "Milk", "Banana", "Cinnamon", "Honey", "Walnuts"], instructions: "Combine oats and milk in a saucepan and cook over medium heat, stirring occasionally until the oats become soft and creamy. Pour the oatmeal into a bowl and top it with sliced banana. Sprinkle cinnamon over the top and drizzle with honey. Finish with chopped walnuts for crunch and serve warm." },
  { title: "Grilled Salmon", ingredientNames: ["Salmon", "Olive oil", "Lemon", "Dill", "Salt", "Black pepper"], instructions: "Brush the salmon fillets lightly with olive oil and season them with salt and black pepper. Place the fish on a preheated grill and cook for about 4–5 minutes per side until the salmon flakes easily with a fork. Transfer to a plate and finish with fresh dill and a squeeze of lemon juice before serving." },
  { title: "Mac and Cheese", ingredientNames: ["Elbow macaroni", "Cheddar cheese", "Milk", "Butter", "Flour", "Salt"], instructions: "Cook the elbow macaroni in salted boiling water until tender, then drain. In a saucepan, melt butter and stir in flour to form a roux, cooking briefly until smooth. Gradually whisk in the milk and cook until the sauce thickens, then stir in shredded cheddar cheese until melted. Combine the cheese sauce with the pasta and serve, or transfer to a baking dish and bake until bubbly." },
  { title: "Caesar Salad", ingredientNames: ["Romaine", "Parmesan", "Caesar dressing", "Bread", "Lemon juice", "Black pepper"], instructions: "Chop the romaine lettuce and place it in a large bowl. Add Caesar dressing and toss until the leaves are evenly coated. Top with grated Parmesan cheese and crunchy croutons made from toasted bread. Finish with a squeeze of lemon juice and a sprinkle of black pepper before serving." },
  { title: "Chicken Curry", ingredientNames: ["Chicken breast", "Curry powder", "Coconut milk", "Onion", "Garlic", "Ginger", "Rice"], instructions: "Heat oil in a skillet and sauté chopped onion, minced garlic, and grated ginger until fragrant. Add pieces of chicken breast and curry powder, stirring to coat the chicken with the spices as it cooks. Pour in the coconut milk and let the curry simmer gently for about 20 minutes until the chicken is tender and the sauce thickens. Serve the curry hot over cooked rice." },
  { title: "Hummus Wrap", ingredientNames: ["Tortilla", "Hummus", "Cucumber", "Tomato", "Lettuce", "Feta cheese"], instructions: "Lay the tortilla flat and spread a generous layer of hummus evenly across the surface. Add sliced cucumber, diced tomato, fresh lettuce, and crumbled feta cheese in a line across the center. Carefully roll the tortilla tightly, folding in the sides if desired to keep the filling inside. Slice in half and serve immediately." },
  { title: "Stuffed Bell Peppers", ingredientNames: ["Bell pepper", "Ground beef", "Rice", "Tomato sauce", "Onion", "Garlic", "Cheese"], instructions: "Cut the tops off the bell peppers and remove the seeds to hollow them out. In a bowl, mix the ground beef with cooked rice, tomato sauce, chopped onion, and minced garlic until well combined. Stuff the mixture firmly into each pepper and place them in a baking dish. Sprinkle cheese on top and bake at 350°F for about 45 minutes until the peppers are tender and the filling is cooked through." },
  { title: "Cream of Mushroom Soup", ingredientNames: ["Mushrooms", "Heavy cream", "Onion", "Garlic", "Butter", "Flour", "Chicken broth"], instructions: "Melt butter in a pot over medium heat and sauté the sliced mushrooms, chopped onion, and minced garlic until softened and fragrant. Stir in the flour and cook briefly to form a light roux, then gradually pour in the chicken broth while stirring to avoid lumps. Let the soup simmer for several minutes before blending until smooth if desired. Stir in the heavy cream and heat gently before serving." },
  { title: "Teriyaki Chicken", ingredientNames: ["Chicken breast", "Soy sauce", "Honey", "Garlic", "Ginger", "Rice vinegar", "Sesame seeds", "Rice"], instructions: "In a small bowl, mix soy sauce, honey, minced garlic, grated ginger, and rice vinegar to create the teriyaki sauce. Cook the chicken breast pieces in a skillet over medium heat until browned and cooked through. Pour the sauce over the chicken and simmer until it thickens and coats the meat with a glossy glaze. Serve the chicken over rice and sprinkle with sesame seeds." },
  { title: "Black Bean Soup", ingredientNames: ["Black beans", "Onion", "Garlic", "Cumin", "Chicken broth", "Lime", "Cilantro"], instructions: "Heat oil in a pot and sauté chopped onion and minced garlic until soft and fragrant. Add the black beans, chicken broth, and cumin, then bring the soup to a gentle simmer for about 20 minutes to blend the flavors. Blend about half of the soup for a thicker texture while leaving some beans whole. Finish with fresh lime juice and chopped cilantro before serving." },
  { title: "Egg Salad", ingredientNames: ["Eggs", "Mayonnaise", "Mustard", "Celery", "Salt", "Black pepper"], instructions: "Boil the eggs until hard-cooked, then cool, peel, and chop them into small pieces. Place the eggs in a bowl and add mayonnaise, mustard, and finely chopped celery. Stir gently until everything is well combined and creamy. Season with salt and black pepper to taste, then serve on bread, toast, or a bed of greens." },
  { title: "Chicken Fajitas", ingredientNames: ["Chicken breast", "Bell pepper", "Onion", "Tortilla", "Lime", "Cumin", "Chili powder"], instructions: "Season sliced chicken breast with cumin and chili powder. Cook the chicken in a hot skillet until browned and cooked through, then remove and set aside. In the same pan, sauté sliced bell peppers and onions until tender-crisp. Return the chicken to the pan, toss everything together, and serve in warm tortillas with a squeeze of lime." },
  { title: "Ramen", ingredientNames: ["Ramen noodles", "Chicken broth", "Eggs", "Green onions", "Soy sauce", "Sesame oil", "Sesame seeds"], instructions: "Cook the ramen noodles according to package directions and set them aside. In a saucepan, heat the chicken broth and stir in soy sauce and sesame oil for flavor. Divide the noodles into bowls and pour the hot broth over them. Top with a soft-boiled or halved egg, sliced green onions, and a sprinkle of sesame seeds before serving." },
  { title: "Bruschetta", ingredientNames: ["Bread", "Tomato", "Basil", "Garlic", "Olive oil", "Balsamic vinegar", "Salt"], instructions: "Slice the bread and toast it until crisp and lightly golden. In a bowl, mix diced tomatoes with chopped basil, minced garlic, olive oil, balsamic vinegar, and a pinch of salt. Spoon the tomato mixture onto each piece of toasted bread. Serve immediately as a fresh appetizer." },
  { title: "Shepherd's Pie", ingredientNames: ["Ground beef", "Potato", "Carrots", "Peas", "Onion", "Beef broth", "Tomato paste", "Butter", "Milk"], instructions: "Cook the ground beef with chopped onion in a skillet until browned, then add carrots, peas, beef broth, and tomato paste and simmer briefly. Meanwhile, boil the potatoes until tender and mash them with butter and milk until smooth. Spread the beef mixture in a baking dish and top evenly with the mashed potatoes. Bake at 375°F for about 25 minutes until the top is lightly golden." },
  { title: "Pad Thai", ingredientNames: ["Rice noodles", "Shrimp", "Eggs", "Fish sauce", "Lime", "Peanuts", "Snap peas"], instructions: "Cook the rice noodles according to package instructions and drain. In a large skillet or wok, stir-fry the shrimp until just cooked, then push them to the side and scramble the eggs. Add the noodles to the pan along with fish sauce and toss everything together until heated through. Serve topped with lime wedges, chopped peanuts, and fresh vegetables." },
  { title: "Coleslaw", ingredientNames: ["Cabbage", "Carrots", "Mayonnaise", "Vinegar", "Sugar", "Salt"], instructions: "Shred the cabbage and carrots and place them in a large mixing bowl. In a separate bowl, whisk together mayonnaise, vinegar, sugar, and a pinch of salt to create the dressing. Pour the dressing over the vegetables and toss until evenly coated. Refrigerate for at least 30 minutes before serving to let the flavors develop." },
  { title: "Chicken Parmesan", ingredientNames: ["Chicken breast", "Marinara sauce", "Mozzarella", "Parmesan", "Breadcrumbs", "Eggs", "Flour"], instructions: "Coat the chicken breasts first in flour, then dip in beaten eggs, and finally cover with breadcrumbs. Fry the breaded chicken in a skillet until golden and crispy on both sides. Transfer the chicken to a baking dish, spoon marinara sauce over the top, and sprinkle with mozzarella and Parmesan cheese. Bake at 375°F for about 20 minutes until the cheese melts and the chicken is cooked through." },
  { title: "Gazpacho", ingredientNames: ["Tomato", "Cucumber", "Bell pepper", "Onion", "Garlic", "Olive oil", "Vinegar", "Bread"], instructions: "Place chopped tomatoes, cucumber, bell pepper, onion, and garlic into a blender and blend until smooth. Add olive oil, vinegar, and a small piece of bread to help thicken the soup. Blend again until the mixture is creamy and well combined. Chill the gazpacho in the refrigerator before serving cold." },
  { title: "Fried Rice", ingredientNames: ["Rice", "Eggs", "Soy sauce", "Peas", "Carrots", "Green onions", "Sesame oil"], instructions: "Heat oil in a large skillet and scramble the eggs until just cooked, then set them aside. Stir-fry the day-old rice with peas and diced carrots, breaking up any clumps as it cooks. Return the eggs to the pan and add soy sauce and sesame oil, tossing everything together. Finish with chopped green onions and serve hot." },
  { title: "Tuna Melt", ingredientNames: ["Canned tuna", "Mayonnaise", "Celery", "Bread", "Cheddar cheese", "Butter"], instructions: "Drain the tuna and mix it with mayonnaise and finely chopped celery in a bowl. Spread the tuna mixture onto slices of bread and top with cheddar cheese. Butter the outside of the bread and cook the sandwich in a skillet until golden and crispy. Flip once so the cheese melts and the bread is toasted on both sides." },
  { title: "Chicken Salad", ingredientNames: ["Chicken breast", "Mayonnaise", "Celery", "Grapes", "Walnuts", "Salt", "Black pepper"], instructions: "Shred or dice the cooked chicken breast and place it in a bowl. Add mayonnaise, chopped celery, halved grapes, and walnuts, then mix until evenly combined. Season with salt and black pepper to taste. Serve the chicken salad on sandwiches, wraps, or over lettuce." },
  { title: "Vegetable Curry", ingredientNames: ["Potato", "Chickpeas", "Coconut milk", "Curry powder", "Onion", "Garlic", "Tomato", "Rice"], instructions: "Sauté chopped onion and minced garlic in a pot with curry powder until fragrant. Add diced potatoes, chickpeas, chopped tomatoes, and coconut milk, stirring well to combine. Let the curry simmer gently for about 25 minutes until the vegetables are tender and the sauce thickens. Serve hot over cooked rice." },
  { title: "Breakfast Burrito", ingredientNames: ["Tortilla", "Eggs", "Bacon", "Cheese", "Salsa", "Avocado"], instructions: "Scramble the eggs in a skillet until softly cooked and cook the bacon until crispy. Warm the tortilla in a pan or microwave so it becomes flexible. Place the eggs, bacon, shredded cheese, salsa, and sliced avocado in the center of the tortilla. Roll it tightly into a burrito and serve warm." },
  { title: "Clam Chowder", ingredientNames: ["Clams", "Potato", "Heavy cream", "Bacon", "Onion", "Celery", "Butter"], instructions: "Cook chopped bacon in a pot until crispy, then add butter along with diced onion and celery and sauté until softened. Add diced potatoes and clam juice or broth, then simmer until the potatoes are tender. Stir in the clams and heavy cream and heat gently without boiling. Serve the chowder warm with bread if desired." },
  { title: "Ratatouille", ingredientNames: ["Eggplant", "Zucchini", "Tomato", "Bell pepper", "Onion", "Garlic", "Basil", "Olive oil"], instructions: "Slice the eggplant, zucchini, tomatoes, and bell peppers into thin rounds. In a baking dish, layer the vegetables with chopped onion and minced garlic, slightly overlapping them for even cooking. Drizzle olive oil over the top and sprinkle with fresh basil. Bake at 375°F for about 45 minutes until the vegetables are tender and flavorful." },
  { title: "Pulled Pork", ingredientNames: ["Pork shoulder", "Barbecue sauce", "Onion", "Garlic", "Brown sugar", "Hamburger bun"], instructions: "Season the pork shoulder with spices and place it in a slow cooker with sliced onion and minced garlic. Cook on low for about 8 hours until the meat becomes very tender and easy to shred. Remove the pork, shred it with two forks, and mix it with barbecue sauce and a little brown sugar for sweetness. Serve the pulled pork piled onto hamburger buns." },
  { title: "Mushroom Risotto", ingredientNames: ["Arborio rice", "Mushrooms", "Chicken broth", "Parmesan", "Onion", "Garlic", "White wine", "Butter"], instructions: "Sauté sliced mushrooms in a pan with butter until golden, then set them aside. In the same pan, cook chopped onion and garlic until fragrant, then add the Arborio rice and toast it briefly. Pour in white wine and let it absorb before gradually adding warm chicken broth, stirring constantly until the rice becomes creamy and tender. Stir in the cooked mushrooms, Parmesan cheese, and a little butter before serving." },
  { title: "Lasagna", ingredientNames: ["Lasagna noodles", "Ground beef", "Tomato sauce", "Mozzarella", "Ricotta", "Parmesan", "Onion", "Garlic"], instructions: "Cook the ground beef with chopped onion and garlic in a skillet until browned, then stir in tomato sauce and simmer briefly. In a baking dish, layer cooked lasagna noodles with the meat sauce, ricotta cheese, and shredded mozzarella. Repeat the layers until the dish is filled and finish with a generous sprinkle of Parmesan on top. Bake at 375°F for about 45 minutes until bubbly and golden." },
  { title: "Chicken Soup", ingredientNames: ["Chicken breast", "Chicken broth", "Carrots", "Celery", "Onion", "Rice", "Thyme"], instructions: "Sauté chopped onion, carrots, and celery in a large pot until softened. Add chicken broth and the chicken breast, then bring the mixture to a gentle simmer. Stir in the rice and thyme and cook until the rice is tender and the chicken is fully cooked. Remove the chicken, shred it, return it to the soup, and serve warm." },
  { title: "Tuna Pasta", ingredientNames: ["Pasta", "Canned tuna", "Garlic", "Olive oil", "Lemon", "Parsley", "Capers"], instructions: "Cook the pasta in salted boiling water until al dente and drain. In a skillet, heat olive oil and sauté minced garlic until fragrant. Add the tuna and break it apart gently, then toss in the cooked pasta. Finish with a squeeze of lemon juice, chopped parsley, and capers before serving." },
  { title: "Corn Chowder", ingredientNames: ["Corn", "Potato", "Heavy cream", "Bacon", "Onion", "Butter", "Chicken broth"], instructions: "Cook chopped bacon in a pot until crispy, then remove it and sauté diced onion in the remaining fat with a little butter. Add diced potatoes, corn, and chicken broth, then simmer until the potatoes are tender. Stir in the heavy cream and return the bacon to the pot. Heat gently and serve warm." },
  { title: "Stir Fry Vegetables", ingredientNames: ["Broccoli", "Bell pepper", "Carrots", "Soy sauce", "Garlic", "Ginger", "Sesame oil", "Rice"], instructions: "Heat oil in a wok or large skillet and stir-fry the broccoli, bell peppers, and carrots over high heat until tender-crisp. Add minced garlic and grated ginger and cook briefly until fragrant. Pour in soy sauce and toss the vegetables so they are evenly coated. Finish with a drizzle of sesame oil and serve over cooked rice." },
  { title: "Eggplant Parmesan", ingredientNames: ["Eggplant", "Marinara sauce", "Mozzarella", "Parmesan", "Breadcrumbs", "Eggs", "Flour"], instructions: "Slice the eggplant and coat each piece in flour, dip in beaten eggs, and cover with breadcrumbs. Fry the slices in a skillet until golden and crispy on both sides. In a baking dish, layer the eggplant with marinara sauce and mozzarella cheese. Finish with Parmesan on top and bake at 375°F for about 25 minutes until bubbly." },
  { title: "Peanut Butter Sandwich", ingredientNames: ["Bread", "Peanut butter", "Jelly"], instructions: "Spread peanut butter evenly on one slice of bread and jelly on the other slice. Place the slices together with the fillings facing inward. Press gently so the sandwich holds together. Slice if desired and serve." },
  { title: "Banana Smoothie", ingredientNames: ["Banana", "Milk", "Yogurt", "Honey", "Ice"], instructions: "Place the banana, milk, yogurt, honey, and ice into a blender. Blend on high speed until the mixture becomes smooth and creamy. Taste and adjust sweetness if needed by adding more honey. Pour into a glass and serve immediately." },
  { title: "Guacamole", ingredientNames: ["Avocado", "Lime", "Tomato", "Onion", "Cilantro", "Salt", "Garlic"], instructions: "Mash the ripe avocados in a bowl until mostly smooth but still slightly chunky. Stir in lime juice, diced tomato, finely chopped onion, cilantro, minced garlic, and salt. Mix everything together until well combined. Serve immediately with chips or as a topping for other dishes." },
  { title: "Salsa", ingredientNames: ["Tomato", "Onion", "Jalapeño", "Cilantro", "Lime", "Salt"], instructions: "Dice the tomatoes, onion, and jalapeño and place them in a bowl. Add chopped cilantro and fresh lime juice. Sprinkle with salt and mix everything together until well combined. Chill briefly before serving for the best flavor." },
  { title: "Garlic Bread", ingredientNames: ["Bread", "Butter", "Garlic", "Parsley", "Parmesan"], instructions: "Mix softened butter with minced garlic and chopped parsley until well combined. Spread the mixture evenly over slices of bread. Sprinkle Parmesan cheese on top for extra flavor. Bake in a 350°F oven for about 10 minutes until the bread is crisp and golden." },
  { title: "Rice and Beans", ingredientNames: ["Rice", "Black beans", "Onion", "Garlic", "Cumin", "Cilantro", "Lime"], instructions: "Cook the rice according to package instructions and keep warm. In a skillet, sauté chopped onion and minced garlic until fragrant. Add the black beans and cumin and cook until heated through. Serve the beans over the rice and finish with chopped cilantro and a squeeze of lime." },
  { title: "Chicken Wings", ingredientNames: ["Chicken wings", "Hot sauce", "Butter", "Garlic powder", "Salt"], instructions: "Season the chicken wings with salt and garlic powder and arrange them on a baking sheet. Bake in a hot oven or fry them until crispy and cooked through. In a separate bowl, mix melted butter with hot sauce. Toss the wings in the sauce until evenly coated and serve immediately." },
  { title: "Tofu Stir Fry", ingredientNames: ["Tofu", "Broccoli", "Bell pepper", "Soy sauce", "Garlic", "Ginger", "Rice"], instructions: "Cut the tofu into cubes and pan-fry it in a skillet until lightly golden on all sides. Remove and set aside while you stir-fry broccoli and bell peppers in the same pan. Add minced garlic and grated ginger and cook briefly until fragrant. Return the tofu to the pan, add soy sauce, toss everything together, and serve over rice." },
  { title: "Cucumber Salad", ingredientNames: ["Cucumber", "Vinegar", "Sugar", "Dill", "Salt", "Onion"], instructions: "Thinly slice the cucumber and onion and place them in a bowl. In a separate bowl, mix vinegar, sugar, dill, and salt until the sugar dissolves. Pour the dressing over the cucumbers and toss gently. Refrigerate for a short time before serving so the flavors can develop." },
  { title: "Tomato Soup", ingredientNames: ["Tomato", "Onion", "Garlic", "Chicken broth", "Heavy cream", "Basil", "Salt"], instructions: "Sauté chopped onion and minced garlic in a pot until soft and fragrant. Add chopped tomatoes and chicken broth and bring the mixture to a simmer. Cook for several minutes before blending until smooth. Stir in heavy cream and fresh basil, season with salt, and serve warm." },
  { title: "Waffles", ingredientNames: ["Flour", "Eggs", "Milk", "Baking powder", "Butter", "Maple syrup"], instructions: "In a bowl, whisk together the flour and baking powder, then mix in the eggs, milk, and melted butter until a smooth batter forms. Preheat and lightly grease a waffle iron, then pour in enough batter to fill the grid. Cook until the waffles are golden and crisp on the outside. Serve warm with maple syrup." },
  { title: "Nachos", ingredientNames: ["Tortilla chips", "Cheese", "Black beans", "Salsa", "Sour cream", "Jalapeño", "Cilantro"], instructions: "Spread tortilla chips evenly on a baking sheet and layer them with shredded cheese and black beans. Bake in a preheated oven until the cheese is melted and bubbly. Remove from the oven and top with salsa, sour cream, sliced jalapeños, and fresh cilantro before serving." },
  { title: "Chili", ingredientNames: ["Ground beef", "Kidney beans", "Tomato", "Onion", "Chili powder", "Cumin", "Garlic"], instructions: "In a large pot over medium heat, brown the ground beef until cooked through. Add chopped onion, garlic, chili powder, and cumin, cooking until fragrant and the onion softens. Stir in the tomatoes and kidney beans, then let the mixture simmer for about 30 minutes so the flavors blend and the chili thickens." },
  { title: "Cottage Cheese Bowl", ingredientNames: ["Cottage cheese", "Tomato", "Cucumber", "Salt", "Black pepper"], instructions: "Spoon cottage cheese into a bowl and spread it out evenly. Dice the tomato and cucumber and scatter them over the top. Season with a pinch of salt and freshly ground black pepper, then serve immediately as a simple fresh bowl." },
  { title: "Yogurt Parfait", ingredientNames: ["Yogurt", "Granola", "Blueberries", "Honey"], instructions: "Spoon a layer of yogurt into a glass or bowl, then add a layer of granola and a handful of blueberries. Repeat the layers until the container is filled. Finish by drizzling honey over the top and serve immediately for a crunchy, sweet parfait." },
  { title: "Turkey Chili", ingredientNames: ["Ground turkey", "Kidney beans", "Tomato", "Onion", "Chili powder", "Cumin"], instructions: "Cook the ground turkey in a large pot over medium heat until browned. Add chopped onion along with the chili powder and cumin, cooking until the onion softens and the spices become fragrant. Stir in the tomatoes and kidney beans and simmer for about 25 minutes until the chili thickens." },
  { title: "Spinach Omelette", ingredientNames: ["Eggs", "Spinach", "Cheese", "Butter", "Salt", "Black pepper"], instructions: "Melt butter in a skillet and sauté the spinach until wilted. Beat the eggs with salt and pepper, then pour them into the pan over the spinach and cook until the eggs begin to set. Sprinkle cheese over one side, fold the omelette in half, and cook briefly until the cheese melts before serving." },
  { title: "Pizza Margherita", ingredientNames: ["Pizza dough", "Tomato sauce", "Mozzarella", "Basil", "Olive oil"], instructions: "Stretch the pizza dough into a thin round and place it on a baking surface. Spread tomato sauce over the dough and top with slices or shreds of mozzarella. Bake in a hot 475°F oven for about 12 minutes until the crust is crisp and the cheese bubbles, then finish with fresh basil and a drizzle of olive oil." },
  { title: "Pork Tenderloin", ingredientNames: ["Pork tenderloin", "Garlic", "Rosemary", "Olive oil", "Salt", "Black pepper"], instructions: "Rub the pork tenderloin with minced garlic, chopped rosemary, olive oil, salt, and black pepper so it is evenly coated. Place it in a roasting pan and roast in a 400°F oven for about 25 minutes until cooked through. Let the meat rest for about 10 minutes before slicing to keep it juicy." },
  { title: "Green Beans Almondine", ingredientNames: ["Green beans", "Almonds", "Butter", "Lemon", "Salt"], instructions: "Blanch the green beans in boiling salted water until tender-crisp, then drain. In a skillet, melt butter and toast the almonds until lightly golden and fragrant. Toss the green beans in the almond butter mixture and finish with a squeeze of lemon and a pinch of salt before serving." },
  { title: "Roasted Vegetables", ingredientNames: ["Broccoli", "Carrots", "Bell pepper", "Zucchini", "Olive oil", "Salt", "Black pepper"], instructions: "Cut the vegetables into evenly sized pieces and toss them in a bowl with olive oil, salt, and black pepper. Spread them out on a baking sheet in a single layer. Roast in a 425°F oven for about 25 minutes, stirring once, until tender and lightly caramelized." },
  { title: "Creamy Polenta", ingredientNames: ["Polenta", "Chicken broth", "Butter", "Parmesan", "Salt"], instructions: "Bring the chicken broth to a gentle boil in a saucepan. Gradually whisk in the polenta, stirring constantly to prevent lumps, and cook until thick and creamy. Finish by stirring in butter, grated Parmesan, and a pinch of salt before serving warm." },
  { title: "Lemon Chicken", ingredientNames: ["Chicken breast", "Lemon", "Garlic", "Thyme", "Olive oil", "Chicken broth"], instructions: "Heat olive oil in a skillet and sear the chicken breasts until golden on both sides. Add minced garlic, fresh lemon juice, thyme, and chicken broth to the pan. Let everything simmer until the chicken is fully cooked and the sauce reduces slightly, then serve with the lemony pan sauce." },
  { title: "Mediterranean Bowl", ingredientNames: ["Quinoa", "Chickpeas", "Cucumber", "Tomato", "Feta cheese", "Olives", "Olive oil"], instructions: "Cook the quinoa according to package instructions and fluff it with a fork. Place it in a bowl and top with chickpeas, diced cucumber, chopped tomato, crumbled feta, and olives. Finish with a drizzle of olive oil and serve as a fresh, balanced bowl." },
  { title: "Beef and Broccoli", ingredientNames: ["Beef steak", "Broccoli", "Soy sauce", "Garlic", "Ginger", "Sesame oil", "Rice"], instructions: "Slice the beef thinly and stir-fry it in a hot pan with a little oil until browned, then remove and set aside. Add broccoli to the pan and cook until just tender. Return the beef to the pan and stir in soy sauce, garlic, ginger, and sesame oil, tossing everything together before serving over cooked rice." },
  { title: "Apple Cinnamon Oatmeal", ingredientNames: ["Oats", "Apple", "Cinnamon", "Milk", "Honey", "Walnuts"], instructions: "Bring the milk to a gentle simmer and stir in the oats, cooking until they become soft and creamy. Add diced apple and cinnamon during the last few minutes so the apple softens slightly. Serve the oatmeal topped with a drizzle of honey and a sprinkle of chopped walnuts." },
  { title: "Shrimp Fried Rice", ingredientNames: ["Rice", "Shrimp", "Eggs", "Soy sauce", "Peas", "Green onions", "Sesame oil"], instructions: "Cook the shrimp in a hot pan until pink and set them aside. Scramble the eggs in the same pan, then add the cooked rice and stir-fry it while breaking up any clumps. Mix in the shrimp, soy sauce, peas, and sliced green onions, finishing with a drizzle of sesame oil before serving." },
  { title: "Cabbage Soup", ingredientNames: ["Cabbage", "Tomato", "Onion", "Carrots", "Vegetable broth", "Garlic", "Thyme"], instructions: "In a large pot, sauté the onion, carrots, and garlic until softened and fragrant. Add chopped cabbage, tomatoes, vegetable broth, and thyme, stirring well. Bring the soup to a simmer and cook for about 30 minutes until the vegetables are tender and the flavors have blended." },
  { title: "Baked Potato", ingredientNames: ["Potato", "Butter", "Sour cream", "Cheddar cheese", "Bacon", "Green onions"], instructions: "Scrub the potato and bake it in a 400°F oven for about an hour until tender when pierced. Split the potato open and fluff the inside with a fork. Top with butter, sour cream, shredded cheddar, crispy bacon, and chopped green onions before serving." },
  { title: "Mango Salsa", ingredientNames: ["Mango", "Tomato", "Red onion", "Cilantro", "Lime", "Jalapeño", "Salt"], instructions: "Dice the mango, tomato, and red onion into small pieces and place them in a bowl. Add chopped cilantro, finely sliced jalapeño, fresh lime juice, and a pinch of salt. Stir everything together and chill briefly before serving for the best flavor." },
  { title: "Thai Basil Chicken", ingredientNames: ["Chicken breast", "Basil", "Garlic", "Fish sauce", "Soy sauce", "Rice", "Chili"], instructions: "Cut the chicken into small pieces and stir-fry it in a hot pan until lightly browned. Add minced garlic, chopped chili, fish sauce, and soy sauce, cooking until fragrant and well combined. Toss in fresh basil leaves and cook briefly until wilted, then serve the flavorful chicken over a bowl of hot rice." },
  { title: "Zucchini Boats", ingredientNames: ["Zucchini", "Ground beef", "Tomato sauce", "Onion", "Cheese"], instructions: "Slice the zucchini in half lengthwise and scoop out the centers to form boats. In a pan, cook the ground beef with chopped onion until browned, then stir in the tomato sauce. Fill the zucchini halves with the beef mixture, sprinkle cheese on top, and bake at 375°F for about 30 minutes until the zucchini is tender and the cheese is melted." },
  { title: "Ceviche", ingredientNames: ["Shrimp", "Lime", "Tomato", "Onion", "Cilantro", "Jalapeño", "Salt"], instructions: "Chop the shrimp into small pieces and place them in a bowl with fresh lime juice, letting them marinate for about 15 minutes until they turn opaque. Stir in diced tomato, onion, chopped cilantro, and sliced jalapeño. Season with salt, mix well, and chill before serving for a refreshing ceviche." },
  { title: "Falafel", ingredientNames: ["Chickpeas", "Garlic", "Cumin", "Cilantro", "Flour", "Olive oil"], instructions: "Blend chickpeas with garlic, cumin, and fresh cilantro in a food processor until a coarse mixture forms. Shape the mixture into small balls or patties and lightly coat them with flour. Fry them in hot oil until golden brown and crisp on the outside, then drain and serve warm." },
  { title: "Baba Ganoush", ingredientNames: ["Eggplant", "Tahini", "Lemon", "Garlic", "Olive oil", "Salt"], instructions: "Roast the eggplant until the flesh is soft and slightly smoky, then scoop it out of the skin. Blend the eggplant with tahini, lemon juice, garlic, olive oil, and a pinch of salt until smooth and creamy. Transfer to a bowl and drizzle with additional olive oil before serving." },
  { title: "Stuffed Mushrooms", ingredientNames: ["Mushrooms", "Cream cheese", "Garlic", "Parsley", "Breadcrumbs"], instructions: "Remove the stems from the mushrooms and place the caps on a baking sheet. In a bowl, mix cream cheese with minced garlic, chopped parsley, and breadcrumbs until well combined. Spoon the filling into each mushroom cap and bake at 375°F for about 20 minutes until the tops are lightly golden." },
  { title: "Antipasto Salad", ingredientNames: ["Lettuce", "Salami", "Mozzarella", "Olives", "Artichoke hearts", "Olive oil", "Vinegar"], instructions: "Arrange a bed of lettuce in a large bowl or platter. Scatter slices of salami, mozzarella pieces, olives, and artichoke hearts evenly over the greens. Drizzle with olive oil and vinegar just before serving and toss lightly to coat everything." },
  { title: "Corn on the Cob", ingredientNames: ["Corn", "Butter", "Salt", "Black pepper"], instructions: "Bring a pot of salted water to a boil or preheat a grill. Cook the corn until the kernels are tender and bright, then remove and let cool slightly. Spread butter over the hot corn and season with salt and black pepper before serving." },
  { title: "Sweet Potato Fries", ingredientNames: ["Sweet potato", "Olive oil", "Salt", "Paprika"], instructions: "Cut the sweet potatoes into fry-shaped sticks and place them in a bowl. Toss them with olive oil, salt, and paprika until evenly coated. Spread them on a baking sheet and bake at 425°F for about 25 minutes, turning once, until crisp on the edges." },
  { title: "Garlic Roasted Potatoes", ingredientNames: ["Potato", "Garlic", "Olive oil", "Rosemary", "Salt", "Black pepper"], instructions: "Cut the potatoes into bite-sized pieces and place them in a bowl. Toss with minced garlic, olive oil, chopped rosemary, salt, and black pepper until evenly coated. Spread on a baking sheet and roast at 425°F for about 35 minutes until crispy outside and tender inside." },
  { title: "Asparagus with Hollandaise", ingredientNames: ["Asparagus", "Butter", "Egg yolks", "Lemon juice", "Salt"], instructions: "Steam the asparagus until bright green and just tender, then set aside. In a small bowl over gentle heat, whisk egg yolks with melted butter and lemon juice until thick and creamy to make the hollandaise. Season with salt and drizzle the sauce over the asparagus before serving." },
  { title: "Cauliflower Rice", ingredientNames: ["Cauliflower", "Olive oil", "Garlic", "Salt"], instructions: "Pulse cauliflower florets in a food processor until they resemble rice-sized grains. Heat olive oil in a skillet and sauté minced garlic until fragrant. Add the cauliflower rice and cook for several minutes, stirring often, until tender, then season with salt before serving." },
  { title: "Kale Salad", ingredientNames: ["Kale", "Lemon juice", "Olive oil", "Parmesan", "Salt"], instructions: "Remove the tough stems from the kale and chop the leaves into bite-sized pieces. Massage them with lemon juice and olive oil until the leaves soften slightly. Add grated Parmesan and a pinch of salt, toss well, and let the salad sit for a few minutes before serving." },
  { title: "Waldorf Salad", ingredientNames: ["Apple", "Celery", "Walnuts", "Mayonnaise", "Lemon juice"], instructions: "Dice the apples and celery into small pieces and place them in a bowl. Add chopped walnuts and toss everything together. Stir in mayonnaise and lemon juice until lightly coated, then chill briefly before serving." },
  { title: "Deviled Eggs", ingredientNames: ["Eggs", "Mayonnaise", "Mustard", "Paprika", "Salt"], instructions: "Boil the eggs until hard-cooked, then peel and cut them in half lengthwise. Remove the yolks and mash them with mayonnaise, mustard, and a pinch of salt until smooth. Spoon or pipe the mixture back into the egg whites and sprinkle lightly with paprika before serving." },
  { title: "Stuffed Tomatoes", ingredientNames: ["Tomato", "Rice", "Ground beef", "Onion", "Garlic", "Basil"], instructions: "Cut the tops off the tomatoes and scoop out the centers to create hollow shells. In a bowl, mix cooked rice with browned ground beef, chopped onion, garlic, and basil. Fill the tomatoes with the mixture, place them in a baking dish, and bake at 375°F for about 30 minutes." },
  { title: "Cajun Shrimp", ingredientNames: ["Shrimp", "Cajun seasoning", "Butter", "Garlic", "Lemon"], instructions: "Toss the shrimp with Cajun seasoning until well coated. Melt butter in a skillet and sauté minced garlic until fragrant, then add the shrimp and cook until pink and cooked through. Finish with a squeeze of fresh lemon juice before serving." },
  { title: "Lemon Herb Roasted Chicken", ingredientNames: ["Chicken thighs", "Lemon", "Thyme", "Rosemary", "Garlic", "Olive oil"], instructions: "Rub the chicken thighs with olive oil, minced garlic, lemon juice, thyme, and rosemary until evenly coated. Place them on a baking sheet or roasting pan. Roast in a 425°F oven for about 40 minutes until the skin is crisp and the chicken is fully cooked." },
  { title: "Mushroom Pasta", ingredientNames: ["Pasta", "Mushrooms", "Garlic", "Cream", "Parmesan", "Parsley"], instructions: "Cook the pasta in salted boiling water until al dente and reserve a little pasta water. In a skillet, sauté sliced mushrooms and garlic until browned and fragrant. Add cream and Parmesan to create a sauce, then toss in the pasta and finish with chopped parsley before serving." },
  { title: "Sloppy Joes", ingredientNames: ["Ground beef", "Tomato sauce", "Onion", "Mustard", "Brown sugar", "Hamburger bun"], instructions: "Brown the ground beef in a skillet with chopped onion until the meat is fully cooked and the onion is soft. Stir in tomato sauce, mustard, and brown sugar and let the mixture simmer until thickened. Spoon the saucy beef onto hamburger buns and serve warm." },
  { title: "Meatballs", ingredientNames: ["Ground beef", "Breadcrumbs", "Eggs", "Onion", "Garlic", "Parsley", "Marinara sauce"], instructions: "In a bowl, combine the ground beef with breadcrumbs, egg, finely chopped onion, minced garlic, and parsley, mixing until evenly combined. Form the mixture into small meatballs and place them on a tray. Bake or pan-fry the meatballs until browned and cooked through, then simmer them in marinara sauce for several minutes before serving." },
  { title: "Chicken Thighs", ingredientNames: ["Chicken thighs", "Olive oil", "Paprika", "Garlic powder", "Salt", "Black pepper"], instructions: "Pat the chicken thighs dry and rub them with olive oil, paprika, garlic powder, salt, and black pepper until evenly coated. Place them in a baking dish or skillet skin-side up. Cook in a 400°F oven for about 35 minutes, or until the skin is crispy and the chicken is cooked through." },
  { title: "Coconut Rice", ingredientNames: ["Rice", "Coconut milk", "Water", "Salt"], instructions: "Combine the rice, coconut milk, water, and a pinch of salt in a saucepan. Bring the mixture to a boil, then reduce the heat, cover, and simmer until the rice is tender and the liquid is absorbed. Fluff the rice with a fork before serving." },
  { title: "Garlic Butter Shrimp", ingredientNames: ["Shrimp", "Butter", "Garlic", "Lemon", "Parsley"], instructions: "Melt butter in a skillet over medium heat and sauté minced garlic until fragrant. Add the shrimp and cook for a few minutes, turning them until they become pink and opaque. Finish with a squeeze of lemon juice and chopped parsley before serving." },
  { title: "Broccoli Cheddar Soup", ingredientNames: ["Broccoli", "Cheddar cheese", "Heavy cream", "Onion", "Chicken broth", "Butter"], instructions: "Melt butter in a pot and sauté the chopped onion until soft and translucent. Add chicken broth and broccoli and simmer until the broccoli is tender. Blend the soup until smooth or slightly chunky, then stir in heavy cream and shredded cheddar cheese until melted and creamy." },
  { title: "Spinach Artichoke Dip", ingredientNames: ["Spinach", "Artichoke hearts", "Cream cheese", "Parmesan", "Garlic"], instructions: "In a bowl, combine chopped spinach, artichoke hearts, softened cream cheese, grated Parmesan, and minced garlic until well mixed. Transfer the mixture to a baking dish and spread it evenly. Bake at 350°F for about 25 minutes until hot and lightly golden on top." },
  { title: "Bruschetta Pasta", ingredientNames: ["Pasta", "Tomato", "Basil", "Garlic", "Olive oil", "Balsamic vinegar"], instructions: "Cook the pasta in salted boiling water until al dente and drain. In a bowl, mix diced tomatoes with chopped basil, minced garlic, olive oil, and a splash of balsamic vinegar. Toss the warm pasta with the tomato mixture and serve immediately." },
  { title: "Honey Mustard Chicken", ingredientNames: ["Chicken breast", "Honey", "Dijon mustard", "Garlic", "Salt"], instructions: "Whisk together honey, Dijon mustard, minced garlic, and salt in a small bowl. Coat the chicken breasts evenly with the mixture and place them in a baking dish. Bake at 375°F for about 25 minutes until the chicken is cooked through and glazed." },
  { title: "Pineapple Fried Rice", ingredientNames: ["Rice", "Pineapple", "Shrimp", "Soy sauce", "Eggs", "Peas"], instructions: "Cook the shrimp in a hot skillet until pink and set them aside. Scramble the eggs in the same pan, then add the cooked rice and stir-fry while breaking up clumps. Mix in pineapple chunks, soy sauce, peas, shrimp, and eggs, stirring until everything is heated through." },
  { title: "Carrot Ginger Soup", ingredientNames: ["Carrots", "Ginger", "Onion", "Chicken broth", "Coconut milk", "Salt"], instructions: "Sauté chopped onion and grated ginger in a pot until fragrant and slightly softened. Add sliced carrots and chicken broth, then simmer until the carrots are tender. Blend the soup until smooth and stir in coconut milk and salt before serving." },
  { title: "Greek Yogurt Bowl", ingredientNames: ["Greek yogurt", "Honey", "Walnuts", "Banana", "Cinnamon"], instructions: "Spoon Greek yogurt into a bowl and spread it evenly. Slice the banana and arrange it over the yogurt along with chopped walnuts. Drizzle honey on top and finish with a light sprinkle of cinnamon." },
  { title: "Turkey Wrap", ingredientNames: ["Tortilla", "Deli turkey", "Lettuce", "Tomato", "Cheese", "Mustard"], instructions: "Lay the tortilla flat and layer slices of deli turkey, lettuce, tomato, and cheese across the center. Spread a thin layer of mustard over the fillings. Roll the tortilla tightly into a wrap and slice in half before serving." },
  { title: "Peach Cobbler", ingredientNames: ["Peach", "Flour", "Sugar", "Butter", "Cinnamon", "Baking powder"], instructions: "Slice the peaches and mix them with sugar in a baking dish. In another bowl, combine flour, baking powder, cinnamon, and butter to create a crumbly topping. Spread the topping over the peaches and bake at 375°F for about 35 minutes until golden and bubbly." },
  { title: "Banana Bread", ingredientNames: ["Banana", "Flour", "Sugar", "Eggs", "Butter", "Baking soda", "Walnuts"], instructions: "Mash the ripe bananas in a bowl until smooth. Stir in sugar, melted butter, eggs, flour, and baking soda until a thick batter forms, then fold in chopped walnuts. Pour the batter into a loaf pan and bake at 350°F for about 60 minutes until set." },
  { title: "Chocolate Chip Cookies", ingredientNames: ["Flour", "Butter", "Sugar", "Brown sugar", "Eggs", "Chocolate chips", "Baking soda"], instructions: "Cream the butter with sugar and brown sugar until light and fluffy. Beat in the eggs, then mix in flour, baking soda, and chocolate chips until a soft dough forms. Drop spoonfuls of dough onto a baking sheet and bake at 375°F for about 10 minutes until golden." },
  { title: "Brownies", ingredientNames: ["Flour", "Cocoa powder", "Sugar", "Butter", "Eggs", "Chocolate chips"], instructions: "Melt the butter and mix it with cocoa powder and sugar until smooth. Beat in the eggs, then stir in flour and chocolate chips until just combined. Spread the batter into a baking pan and bake at 350°F for about 30 minutes until set." },
  { title: "Apple Crisp", ingredientNames: ["Apple", "Oats", "Flour", "Brown sugar", "Butter", "Cinnamon"], instructions: "Slice the apples and spread them in a baking dish. In a bowl, combine oats, flour, brown sugar, butter, and cinnamon to form a crumbly topping. Sprinkle the topping evenly over the apples and bake at 375°F for about 35 minutes until golden and bubbly." },
  { title: "Lemon Bars", ingredientNames: ["Flour", "Butter", "Sugar", "Lemon", "Eggs"], instructions: "Mix flour, butter, and sugar to form a dough and press it into a baking pan to create the crust. Bake briefly until lightly set, then pour a lemon mixture made from eggs, sugar, and lemon juice over the top. Return to the oven and bake at 350°F for about 25 minutes until firm." },
  { title: "Rice Pudding", ingredientNames: ["Rice", "Milk", "Sugar", "Cinnamon", "Vanilla extract", "Raisins"], instructions: "Simmer rice in milk over low heat, stirring frequently until the grains become soft and creamy. Add sugar, cinnamon, vanilla extract, and raisins, mixing well. Continue cooking gently until the pudding thickens, then serve warm or chilled." },
  { title: "French Onion Soup", ingredientNames: ["Onion", "Beef broth", "Butter", "Thyme", "Bread", "Gruyère"], instructions: "Cook sliced onions slowly in butter until deeply caramelized and golden brown. Add beef broth and thyme and simmer for several minutes to develop flavor. Ladle the soup into bowls, top with toasted bread and grated Gruyère, and broil until the cheese melts and bubbles." },
  { title: "Pot Roast", ingredientNames: ["Beef chuck", "Potato", "Carrots", "Onion", "Beef broth", "Thyme", "Bay leaves"], instructions: "Sear the beef chuck in a hot pot until browned on all sides. Add chopped potatoes, carrots, onions, beef broth, thyme, and bay leaves, bringing the mixture to a gentle simmer. Cover and braise in the oven or on the stovetop for about 3 hours until the meat is tender and flavorful." },
  { title: "Lamb Chops", ingredientNames: ["Lamb chops", "Garlic", "Rosemary", "Olive oil", "Salt", "Black pepper"], instructions: "Marinate the lamb chops with minced garlic, chopped rosemary, olive oil, salt, and black pepper for at least 30 minutes. Preheat a grill or skillet and cook the chops for about 4 minutes per side until desired doneness. Let rest for a few minutes before serving to retain juices." },
  { title: "Crab Cakes", ingredientNames: ["Crab meat", "Breadcrumbs", "Eggs", "Mayonnaise", "Mustard", "Old Bay seasoning"], instructions: "Combine crab meat with breadcrumbs, beaten eggs, mayonnaise, mustard, and Old Bay seasoning in a bowl. Form the mixture into small patties and carefully pan-fry them in oil until golden brown and crispy on both sides. Serve warm with lemon or sauce of choice." },
  { title: "Clam Pasta", ingredientNames: ["Pasta", "Clams", "Garlic", "White wine", "Parsley", "Olive oil"], instructions: "Cook pasta until al dente and set aside. In a skillet, sauté minced garlic in olive oil, then add clams and white wine, cooking until the clams open. Toss the pasta with the clams and sauce, finish with chopped parsley, and serve immediately." },
  { title: "Mussels in White Wine", ingredientNames: ["Mussels", "White wine", "Garlic", "Butter", "Parsley", "Bread"], instructions: "Sauté minced garlic in butter until fragrant, then add white wine and bring to a simmer. Add cleaned mussels and cover, cooking until the shells open. Sprinkle with chopped parsley and serve hot with crusty bread for dipping." },
  { title: "Scallops", ingredientNames: ["Scallops", "Butter", "Garlic", "Lemon", "Parsley"], instructions: "Pat the scallops dry and sear them in a hot skillet with butter for about 2 minutes per side until golden. Add minced garlic during the last minute of cooking, then finish with a squeeze of lemon and chopped parsley before serving." },
  { title: "Cod with Tomatoes", ingredientNames: ["Cod", "Tomato", "Garlic", "Olive oil", "Basil", "White wine"], instructions: "Sauté minced garlic in olive oil, then add chopped tomatoes and a splash of white wine, cooking until slightly thickened. Place cod fillets in the pan and bake at 375°F for about 15 minutes until the fish flakes easily. Garnish with fresh basil before serving." },
  { title: "Trout Almondine", ingredientNames: ["Trout", "Almonds", "Butter", "Lemon", "Parsley"], instructions: "Pan-fry the trout in butter until cooked through and golden. In the same pan, toast sliced almonds until lightly browned, then add a squeeze of lemon juice and chopped parsley. Pour the almond mixture over the trout and serve immediately." },
  { title: "Salmon Patties", ingredientNames: ["Canned salmon", "Breadcrumbs", "Eggs", "Onion", "Lemon", "Dill"], instructions: "Mix flaked canned salmon with breadcrumbs, beaten eggs, finely chopped onion, and seasonings. Form the mixture into patties and pan-fry until golden brown on both sides. Serve warm with a squeeze of lemon and fresh dill." },
  { title: "Tilapia with Lemon", ingredientNames: ["Tilapia", "Lemon", "Butter", "Garlic", "Parsley"], instructions: "Season tilapia fillets with salt and pepper and pan-fry in butter until cooked through. Add minced garlic during the last minute of cooking, then finish with a squeeze of fresh lemon and a sprinkle of chopped parsley before serving." },
  { title: "Shrimp and Grits", ingredientNames: ["Shrimp", "Grits", "Bacon", "Garlic", "Butter", "Green onions"], instructions: "Cook the grits according to package instructions until creamy. In a skillet, sauté bacon until crisp, then add shrimp and minced garlic, cooking until shrimp turn pink. Serve the shrimp and bacon mixture over the grits and top with butter and sliced green onions." },
  { title: "Jambalaya", ingredientNames: ["Chicken breast", "Shrimp", "Andouille sausage", "Rice", "Onion", "Bell pepper", "Celery", "Cajun seasoning"], instructions: "Sauté diced chicken, andouille sausage, and shrimp with chopped onions, bell peppers, and celery until lightly browned. Stir in rice, add broth and Cajun seasoning, then simmer until the rice is cooked and the flavors meld together. Adjust seasoning before serving hot." },
  { title: "Gumbo", ingredientNames: ["Chicken breast", "Andouille sausage", "Shrimp", "Okra", "Onion", "Bell pepper", "Celery", "Rice"], instructions: "Prepare a roux by cooking flour and oil until golden, then add chopped onion, bell pepper, celery, and okra. Stir in chicken and sausage, add broth, and simmer until flavors develop. Add shrimp at the end and serve the gumbo over steamed rice." },
  { title: "Paella", ingredientNames: ["Rice", "Chicken breast", "Shrimp", "Saffron", "Bell pepper", "Peas", "Tomato"], instructions: "Sauté diced chicken with chopped bell peppers and tomatoes, then add rice and saffron, stirring to coat evenly. Pour in broth and simmer until the rice is nearly cooked. Add shrimp and peas, cooking until shrimp are pink and rice is tender, then serve warm." },
  { title: "Bouillabaisse", ingredientNames: ["Cod", "Shrimp", "Mussels", "Tomato", "Garlic", "Saffron", "Fennel", "Bread"], instructions: "Sauté fennel and garlic in olive oil, then add chopped tomatoes, saffron, and broth, bringing it to a simmer. Add cod, shrimp, and mussels, cooking until the seafood is done. Serve hot with slices of crusty bread." },
  { title: "Fish and Chips", ingredientNames: ["Cod", "Flour", "Beer", "Potato", "Vegetable oil", "Salt"], instructions: "Prepare a beer batter with flour and chilled beer, then coat cod fillets and fry in hot oil until golden and crispy. Cut potatoes into wedges, fry until crisp, and season with salt. Serve the fish and chips together immediately." },
  { title: "Tuna Nicoise", ingredientNames: ["Canned tuna", "Eggs", "Green beans", "Potato", "Olives", "Tomato", "Lemon", "Olive oil"], instructions: "Arrange a bed of lettuce or greens on a plate, then layer with flaked tuna, hard-boiled eggs, blanched green beans, boiled potato slices, olives, and tomato wedges. Drizzle with lemon juice and olive oil before serving." },
  { title: "Sushi Bowl", ingredientNames: ["Rice", "Salmon", "Cucumber", "Avocado", "Soy sauce", "Sesame seeds"], instructions: "Layer cooked sushi rice in a bowl, then top with slices of fresh salmon, diced cucumber, and avocado. Drizzle with soy sauce and sprinkle with sesame seeds before serving for a fresh, deconstructed sushi experience." },
  { title: "Poke Bowl", ingredientNames: ["Tuna", "Rice", "Soy sauce", "Sesame oil", "Green onions", "Avocado", "Cucumber"], instructions: "Place a layer of cooked rice in a bowl, then add cubed raw tuna, sliced avocado, and diced cucumber. Drizzle with a mixture of soy sauce and sesame oil and garnish with chopped green onions before serving." },
  { title: "Cioppino", ingredientNames: ["Shrimp", "Clams", "Mussels", "Cod", "Tomato", "Garlic", "White wine", "Bread"], instructions: "Sauté minced garlic in olive oil, then add chopped tomatoes, white wine, and broth to create a flavorful base. Add cod, shrimp, clams, and mussels, simmering until all seafood is cooked. Serve hot with crusty bread on the side." },
  { title: "Lobster Roll", ingredientNames: ["Lobster", "Mayonnaise", "Celery", "Lemon", "Bread", "Butter"], instructions: "Mix cooked lobster meat with mayonnaise, finely chopped celery, and a squeeze of lemon until well combined. Lightly butter and toast the bread rolls, then fill them with the lobster mixture and serve immediately." },
  { title: "Crab Salad", ingredientNames: ["Crab meat", "Mayonnaise", "Celery", "Lemon juice", "Dill", "Salt"], instructions: "Flake the crab meat into a bowl and combine with mayonnaise, chopped celery, lemon juice, dill, and a pinch of salt. Mix gently and chill before serving on a bed of greens or inside a sandwich." },
  { title: "Oyster Po' Boy", ingredientNames: ["Oysters", "Bread", "Lettuce", "Tomato", "Mayonnaise", "Hot sauce"], instructions: "Fry the oysters until golden and crisp. Layer fresh bread with lettuce, sliced tomato, and mayonnaise, then add the fried oysters on top and drizzle with hot sauce to taste." },
  { title: "Crawfish Boil", ingredientNames: ["Crawfish", "Potato", "Corn", "Onion", "Cajun seasoning", "Lemon"], instructions: "Boil water with Cajun seasoning, then add potatoes, corn, and onions, cooking until tender. Add crawfish at the end and boil until bright red, then drain and serve hot with lemon wedges." },
  { title: "Seafood Paella", ingredientNames: ["Rice", "Shrimp", "Mussels", "Squid", "Saffron", "Bell pepper", "Peas"], instructions: "Sauté chopped bell peppers and other vegetables, then stir in rice and saffron. Gradually add broth while cooking, then layer on shrimp, mussels, and squid until seafood is cooked and rice is tender. Serve warm." },
  { title: "Salmon Sashimi", ingredientNames: ["Salmon", "Soy sauce", "Wasabi", "Ginger"], instructions: "Slice fresh salmon thinly against the grain and arrange neatly on a plate. Serve immediately with soy sauce, a dab of wasabi, and pickled ginger on the side." },
  { title: "Tuna Sashimi", ingredientNames: ["Tuna", "Soy sauce", "Wasabi", "Ginger"], instructions: "Carefully slice fresh tuna into thin pieces and arrange them on a serving plate. Accompany with soy sauce, wasabi, and ginger for dipping and garnish." },
  { title: "Grilled Octopus", ingredientNames: ["Octopus", "Olive oil", "Lemon", "Garlic", "Oregano"], instructions: "Boil the octopus until tender, then grill it with olive oil, minced garlic, and oregano until slightly charred. Finish with a squeeze of fresh lemon before serving." },
  { title: "Calamari", ingredientNames: ["Calamari", "Flour", "Eggs", "Vegetable oil", "Lemon", "Marinara sauce"], instructions: "Coat calamari rings in flour and beaten eggs, then fry in hot oil until golden and crispy. Serve immediately with lemon wedges and a side of marinara sauce for dipping." },
  { title: "Shrimp Cocktail", ingredientNames: ["Shrimp", "Lemon", "Ketchup", "Horseradish", "Worcestershire sauce"], instructions: "Boil shrimp until pink and firm, then chill. Prepare cocktail sauce by mixing ketchup, horseradish, Worcestershire sauce, and a squeeze of lemon, and serve the shrimp chilled with the sauce." },
  { title: "Smoked Salmon Bagel", ingredientNames: ["Bagel", "Cream cheese", "Smoked salmon", "Caper", "Red onion", "Dill"], instructions: "Toast the bagel halves and spread a generous layer of cream cheese on each. Top with slices of smoked salmon, capers, thinly sliced red onion, and a sprinkle of fresh dill before serving." },
  { title: "Crab Rangoon", ingredientNames: ["Crab meat", "Cream cheese", "Wonton wrappers", "Green onions"], instructions: "Mix crab meat, cream cheese, and chopped green onions until well combined. Spoon the mixture into wonton wrappers, fold and seal, then fry until golden brown and crispy." },
  { title: "Shrimp Tempura", ingredientNames: ["Shrimp", "Flour", "Eggs", "Vegetable oil", "Soy sauce", "Ginger"], instructions: "Prepare a light tempura batter with flour and beaten eggs, coat the shrimp, and fry in hot oil until crispy. Serve immediately with soy sauce and freshly grated ginger for dipping." },
  { title: "Fish Tacos with Slaw", ingredientNames: ["Cod", "Tortilla", "Cabbage", "Lime", "Cilantro", "Sour cream"], instructions: "Cook the cod by frying or grilling until done. Toss shredded cabbage with lime juice and chopped cilantro to make a slaw. Assemble tacos by layering fish and slaw in warmed tortillas and topping with sour cream." },
  { title: "Salmon Teriyaki", ingredientNames: ["Salmon", "Soy sauce", "Honey", "Garlic", "Ginger", "Sesame seeds", "Rice"], instructions: "Make a teriyaki glaze with soy sauce, honey, garlic, and ginger. Brush over salmon and bake or grill until cooked through. Serve over rice and sprinkle with toasted sesame seeds." },
  { title: "Tuna Steak", ingredientNames: ["Tuna", "Soy sauce", "Sesame oil", "Green onions", "Ginger"], instructions: "Marinate tuna steaks briefly in soy sauce and sesame oil, then sear quickly on high heat for about a minute per side. Slice and garnish with chopped green onions and fresh ginger before serving." },
  { title: "Halibut with Herbs", ingredientNames: ["Halibut", "Lemon", "Dill", "Parsley", "Olive oil", "Garlic"], instructions: "Season halibut fillets with salt and pepper, top with chopped dill, parsley, minced garlic, and a drizzle of olive oil. Bake at 400°F until the fish is opaque and flakes easily, finishing with a squeeze of lemon." },
  { title: "Swordfish Steak", ingredientNames: ["Swordfish", "Lemon", "Olive oil", "Garlic", "Oregano"], instructions: "Marinate swordfish steaks in olive oil, minced garlic, oregano, and lemon juice. Grill for about 4 minutes per side until nicely seared, and serve with extra lemon wedges." },
  { title: "Mahi Mahi Tacos", ingredientNames: ["Mahi mahi", "Tortilla", "Cabbage", "Lime", "Avocado", "Cilantro"], instructions: "Grill mahi mahi fillets until cooked through and flaky. Warm tortillas, then top with fish, shredded cabbage, avocado slices, a squeeze of lime, and chopped cilantro before serving." },
  { title: "Catfish Po' Boy", ingredientNames: ["Catfish", "Bread", "Lettuce", "Tomato", "Mayonnaise", "Pickles"], instructions: "Fry seasoned catfish fillets until golden and crispy. Layer bread with lettuce, tomato, and mayonnaise, then place the fried catfish on top and add pickles before serving." },
  { title: "Anchovy Pasta", ingredientNames: ["Pasta", "Anchovies", "Garlic", "Olive oil", "Red pepper flakes", "Parsley"], instructions: "Cook pasta until al dente and drain. Sauté garlic and anchovies in olive oil until fragrant, add red pepper flakes, then toss in the pasta and finish with chopped parsley." },
  { title: "Sardine Toast", ingredientNames: ["Bread", "Sardines", "Lemon", "Olive oil", "Parsley"], instructions: "Toast slices of bread and top with sardines. Drizzle with olive oil and a squeeze of lemon, then sprinkle with fresh parsley before serving." },
  { title: "Mackerel with Lemon", ingredientNames: ["Mackerel", "Lemon", "Olive oil", "Garlic", "Rosemary"], instructions: "Season mackerel fillets with salt and pepper, drizzle with olive oil, and top with garlic and rosemary. Bake or grill until cooked through, finishing with a squeeze of lemon." },
  { title: "Herring Salad", ingredientNames: ["Herring", "Sour cream", "Onion", "Apple", "Potato"], instructions: "Dice herring, onion, apple, and boiled potatoes, then mix with sour cream until well combined. Chill in the refrigerator before serving." },
  { title: "Flounder Meuniere", ingredientNames: ["Flounder", "Butter", "Lemon", "Parsley"], instructions: "Dredge flounder fillets in flour and pan-fry in butter until golden. Finish with a squeeze of fresh lemon and a sprinkle of chopped parsley." },
  { title: "Sole Piccata", ingredientNames: ["Sole", "Butter", "Lemon", "Capers", "White wine"], instructions: "Pan-fry sole fillets in butter until lightly browned. Make a sauce with butter, lemon juice, capers, and white wine, and pour over the fish before serving." },
  { title: "Snapper Veracruz", ingredientNames: ["Red snapper", "Tomato", "Olives", "Capers", "Garlic", "White wine"], instructions: "Sauté garlic, then add chopped tomatoes, olives, capers, and white wine to make a sauce. Place snapper fillets in the sauce and bake at 375°F until cooked through." },
  { title: "Grouper with Mango", ingredientNames: ["Grouper", "Mango", "Lime", "Cilantro", "Red onion"], instructions: "Grill grouper fillets until flaky. Prepare a mango salsa with diced mango, red onion, lime juice, and chopped cilantro, and spoon over the fish before serving." },
  { title: "Barramundi with Ginger", ingredientNames: ["Barramundi", "Ginger", "Soy sauce", "Green onions", "Sesame oil"], instructions: "Steam or pan-fry barramundi until cooked through, then top with julienned ginger, soy sauce, chopped green onions, and a drizzle of sesame oil before serving." },
  { title: "Perch Fry", ingredientNames: ["Perch", "Flour", "Eggs", "Breadcrumbs", "Vegetable oil", "Lemon"], instructions: "Coat perch fillets in flour, dip in beaten eggs, then coat with breadcrumbs. Fry in hot oil until golden and crisp, and serve with lemon wedges." },
  { title: "Carp with Paprika", ingredientNames: ["Carp", "Paprika", "Garlic", "Onion", "Tomato"], instructions: "Season carp with paprika and sauté with chopped garlic and onions. Add diced tomatoes and simmer gently until the fish is cooked through and flavorful." },
  { title: "Rainbow Trout", ingredientNames: ["Rainbow trout", "Butter", "Lemon", "Almonds", "Parsley"], instructions: "Stuff the trout with butter and lemon slices, then bake or grill until flaky. Top with toasted almonds and fresh parsley before serving." },
  { title: "Sea Bass with Fennel", ingredientNames: ["Sea bass", "Fennel", "Lemon", "Olive oil", "White wine"], instructions: "Sauté sliced fennel in olive oil, add white wine, and place the sea bass on top. Bake at 375°F until the fish is cooked through and serve with lemon." },
  { title: "Branzino Whole", ingredientNames: ["Branzino", "Lemon", "Garlic", "Olive oil", "Rosemary"], instructions: "Stuff the whole branzino with lemon, garlic, and rosemary, drizzle with olive oil, and roast at 425°F until the fish is tender and aromatic." },
  { title: "Surimi Salad", ingredientNames: ["Surimi", "Cucumber", "Mayonnaise", "Lemon juice", "Dill"], instructions: "Shred surimi and combine with diced cucumber, mayonnaise, lemon juice, and chopped dill. Chill the salad before serving for best flavor." },
  { title: "Veggie Wrap", ingredientNames: ["Tortilla", "Hummus", "Cucumber", "Tomato", "Lettuce", "Carrots"], instructions: "Spread hummus evenly over a tortilla, layer with sliced cucumber, tomato, lettuce, and shredded carrots, then roll tightly and slice to serve." },
  { title: "Peanut Noodles", ingredientNames: ["Spaghetti", "Peanut butter", "Soy sauce", "Lime", "Peanuts", "Cucumber"], instructions: "Cook spaghetti until al dente, then toss with a sauce made from peanut butter, soy sauce, and lime juice. Top with chopped peanuts and sliced cucumber before serving." },
  { title: "Stuffed Acorn Squash", ingredientNames: ["Acorn squash", "Quinoa", "Kale", "Cranberries", "Parmesan"], instructions: "Roast halved acorn squash until tender. Mix cooked quinoa with chopped kale and dried cranberries, stuff the squash, and sprinkle with Parmesan before serving." }
];

async function seed() {
  const uri = process.env.MONGODB_URI;
  const dbName = process.env.DBNAME;
  if (!uri || !dbName) {
    console.error("Missing MONGODB_URI or DBNAME. Set them in .env.local");
    process.exit(1);
  }
  try {
    await mongoose.connect(uri, { dbName });
    const Ingredient = mongoose.models.Ingredient || mongoose.model("Ingredient", new mongoose.Schema({ name: String, image_url: String, addedAt: Date }));
    const Recipe = mongoose.models.Recipe || mongoose.model("Recipe", new mongoose.Schema({ title: String, ingredients: [{ type: mongoose.Schema.Types.ObjectId, ref: "Ingredient" }], instructions: String, createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, createdAt: Date }));
    const User = mongoose.models.User || mongoose.model("User", new mongoose.Schema({ email: String, password: String, firstName: String, lastName: String, createdRecipes: [{ type: mongoose.Schema.Types.ObjectId, ref: "Recipe" }] }));

    const ingredients = await Ingredient.find({}).lean();
    const ingredientMap = new Map();
    ingredients.forEach((i) => { ingredientMap.set(i.name.toLowerCase().trim(), i._id); });

    const existingTitles = new Set((await Recipe.find({ createdBy: USER_ID }, "title").lean()).map((r) => r.title.toLowerCase()));
    let added = 0;
    for (const r of RECIPES) {
      if (existingTitles.has(r.title.toLowerCase())) continue;
      const ids = r.ingredientNames.map((n) => ingredientMap.get(n.toLowerCase().trim())).filter(Boolean);
      if (ids.length === 0) continue;
      const recipe = await Recipe.create({ title: r.title, ingredients: ids, instructions: r.instructions, createdBy: USER_ID });
      await User.findByIdAndUpdate(USER_ID, { $push: { createdRecipes: recipe._id } });
      existingTitles.add(r.title.toLowerCase());
      added++;
    }
    console.log(`Seeded ${added} new recipes. Total: ${await Recipe.countDocuments({ createdBy: USER_ID })}`);
  } catch (err) {
    console.error("Seed failed:", err);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
  }
}
seed();

